services:
  functions:
    environment:
      OCPP_API_KEY: ${OCPP_API_KEY}
      CHARGECMS_READAPI_URL: ${CHARGECMS_READAPI_URL}
      OCPP_ADMIN_INTERNAL_TOKEN: ${OCPP_ADMIN_INTERNAL_TOKEN}
      HONNMONO_ADMIN_API_URL: ${HONNMONO_ADMIN_API_URL}
      HONNMONO_ADMIN_INTERNAL_TOKEN: ${HONNMONO_ADMIN_INTERNAL_TOKEN}
